Traceback (most recent call last):
  File "/home/timothyprojectinfo/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/timothyprojectinfo/.local/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/timothyprojectinfo/.local/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/timothyprojectinfo/.local/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/timothyprojectinfo/.local/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sinewave(1)  #frequency=1 and 1 cycle per second
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [43msinewave[49m[43m([49m[38;5;241;43m1[39;49m[43m)[49m  [38;5;66;03m#frequency=1 and 1 cycle per second[39;00m

Cell [0;32mIn[3], line 8[0m, in [0;36msinewave[0;34m(frequency)[0m
[1;32m      6[0m sound_wave[38;5;241m=[39mnp[38;5;241m.[39msin(frequency[38;5;241m*[39m [38;5;241m2[39m[38;5;241m*[39mnp[38;5;241m.[39mpi[38;5;241m*[39m t)  [38;5;66;03m# mathematical definition of a sine wave[39;00m
[1;32m      7[0m [38;5;66;03m#----------PLOT THE SOUND WAVE----------------------[39;00m
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      9[0m fig[38;5;241m=[39mplt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m2[39m,[38;5;241m1[39m))
[1;32m     10[0m plt[38;5;241m.[39mplot(t,sound_wave)

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

